# CI de Nivel 03 - Disparo apos a conclusao de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilho/triggers)
# gatilho de exec a partir de outro pipe = workflow_run
on:
  workflow_run:
    workflows: ['Execução Manual']
    # nome da pipeline que voce  vai monitorar
    types:
      - completed
      # as types podem ser tbem in_progress, requested

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # nome da nossa tarefa

    if: ${{  github.event.workflow_run.conclusion == 'success' }}

    runs-on:
      ubuntu-latest
      # maquina que iremos executar nossa tarefa

      # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v2

      # instalação do node
      - uses: actions/setup-node@v2
        with:
          node-version: 22.x
      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalando dependências
      - name: Instalando dependências
        run: yarn

      # instalando Playwritght
      - name: Instalando Playwright
        run: yarn  playwright install

      # executando os testes
      - name: Executando os testes E2E
        run: yarn run e2e

      # recurso subir temporariamente arquivo especialmente de relatorio
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: report
          path: ./playwright-report
